EXCLUDE_VERSIONS=3.14.12.5

include ${EPICS_ENV_PATH}/module.Makefile

# Don't include debug symbols in the binary needed for a debugger
# We don't have a debuuger, so shrink the size from 29MB to 9MB under
# /opt/epics/modules
OPT_CXXFLAGS_YES = -O3

PROJECT=exprtk
# Temporally removed to speed up 
EXCLUDE_ARCHS += eldk

HEADERS = exprtkWrap.h

SOURCES = \
  exprtkIF.cpp \
  exprtkImp.cpp \
  exprtkWrap.cpp

